avanceproyidk/Controllers/CarritoController.cs
using AutoMapper;
using avanceproyidk.DataAccess;
using avanceproyidk.Models;
using avanceproyidk.DataAccess.DBEntities;
using Microsoft.AspNetCore.Mvc;
using avanceproyidk.CustomExtensions;

using System;
using System.Collections.Generic;
using System.Linq;

namespace avanceproyidk.Controllers
{

    public class CarritoController : Controller
    {
        private readonly IMapper _mapper;
        private readonly CarritoContext _context;

        
        public CarritoController(CarritoContext context, IMapper mapper)
        {
            _context = context;
            _mapper = mapper;
        }
        public IActionResult CatalogoProducto()
        {
            var productListDB = _context.Producto.Where(c => c.Status == true).ToList();
            var list = _mapper.Map<List<ProductosCatalogosModel>>(productListDB);
            return View(list);
        }


        public IActionResult DetalleProducto(int id)
        {
            var productXid = _context.Producto.Where(c => c.Id == id && c.Status == true).SingleOrDefault();
            var vistaproducto = _mapper.Map<ProductosCatalogosModel>(productXid);
            return View(vistaproducto);
        }


        [HttpPost]
        public JsonResult AddProductoTemporal(ProductosTemporalesModel param)
        {
            // product info
            var productoXid = _context.Producto.Where(c => c.Id == param.Id && c.Status == true).SingleOrDefault();
            param.nombreproducto = productoXid.nombreproducto;
            param.precio = productoXid.preciofinal;
            param.imagen = productoXid.imagen;


            // product list
            List<ProductosTemporalesModel> temporalproducts = null;

            if(HttpContext.Session.GetList<ProductosTemporalesModel>("temporal") == null)
            {
                temporalproducts = new List<ProductosTemporalesModel>();
            }
            else
            {
                temporalproducts = (List<ProductosTemporalesModel>)HttpContext.Session.GetList<ProductosTemporalesModel>("temporal");
            }
            temporalproducts.Add(param);
            HttpContext.Session.Set<List<ProductosTemporalesModel>>("temporal", temporalproducts);
            return new JsonResult(new { a = 1 });

        }

        public IActionResult ConfirmarCarrito()
        {
            var model = new ConfirmarCarritoModel();
            model.TemporalProducts = (List<ProductosTemporalesModel>)HttpContext.Session.GetList<ProductosTemporalesModel>("temporal");
            return View(model);
        }

        
        [HttpPost]
        public IActionResult GuardarCarrito(ConfirmarCarritoModel modelToSave)
        {
            modelToSave.TemporalProducts = (List<ProductosTemporalesModel>)HttpContext.Session.GetList<ProductosTemporalesModel>("temporal");

            // guardar user
            var userReg = _context.Usuario.Add(new UsuarioEntity()
            {
                dni = modelToSave.dni,
                nombre = modelToSave.nombre,
                apellido = modelToSave.apellido,
                usuario = modelToSave.usuario,
                contrasena = modelToSave.contrasena,
                Status = true,
            });


            // guardar orden
            var ordenReg = _context.Orden.Add(new OrdenEntity()
            {
                numerotarjeta = modelToSave.numerotarjeta,
                fechaexpiracion = modelToSave.fechaexpiracion,
                cvv = modelToSave.cvv,
                correo = modelToSave.correo,
                fechaOrden = DateTime.Now,
                Usuario = userReg.Entity,
                Status = true
            });

            // guardar productos
            foreach(var item in modelToSave.TemporalProducts)
            {
                _context.OrdenDetalle.Add(new OrdenDetalleEntity()
                {
                    Status = true,
                    preciofinal = item.precio,
                    Orden = ordenReg.Entity,
                    Producto = _context.Producto.Where(c => c.Id == item.Id).FirstOrDefault(),
                });
            }
                
            _context.SaveChanges();

            return RedirectToAction("MsgOrdenExitosa");
        }

        public IActionResult MsgOrdenExitosa()
        {
            return View();
        }
    }
}

avanceproyidk/Views/Carrito/CatalogoProducto.cshtml
@model List<ProductosCatalogosModel>
@{
    ViewData["Title"] = "CatalogoProducto";
}

<h1>Catalogo de VideoJuegos</h1>

<div class="row mt-5">
    @foreach (var item in Model)
    {
        <div class="col-md-3">
            <div class="card mt-2">
                <center>
                    <img class="card-img-top img-fluid" style="width: 130px; height:130px;" src="@item.imagen" alt="@item.nombreproducto">
                </center>
                <div class="card-body">
                    <h5 class="card-title limiter">@item.nombreproducto</h5>
                    <p class="card-text log-limiter">@item.descripcion.Substring(0,40)...</p>

                    <a asp-action="DetalleProducto" asp-controller="Carrito" asp-route-id="@item.idproducto" class="btn btn-success">
                        <i class="fa-solid fa-magnifying-glass"></i> Detalles
                    </a>
                </div>
            </div>
        </div>
    }
</div>

avanceproyidk/Views/Carrito/ConfirmarCarrito.cshtml
@model ConfirmarCarritoModel;

@{
    ViewData["Title"] = "ConfirmarCarrito";
}

<h1>En hora buena por tu compra!!</h1>

<table class="table">
    <thead>
        <tr>
            <th>

            </th>
            <th>
                Producto
            </th>
            <th>
                Precio
            </th>
            <th>
                Cantidad
            </th>
            <th>
                Accion
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.TemporalProducts)
        {
            <tr>
                <td>
                    <img class="card-img-top" src="@item.imagen" style="height:60px; width:60px;" alt="Card image cap">
                </td>
                <td>
                    @item.nombreproducto
                </td>
                <td>
                    @item.precio
                </td>
                <td>
                    @item.cantidad
                </td>
                <td>
                    <button class="btn btn-danger"><i class="fa-solid fa-trash"></i></button>
                </td>
            </tr>
        }
    </tbody>
</table>

<form method="post" asp-action="GuardarCarrito">
    <div class="row">
        <div class="col-md-6">
            <div class="row">
                <div class="col-md-12">
                    <h5><i class="fa-solid fa-circle-info"></i> Información del Cliente</h5>

                    <div class="row">
                        <div class="col-md-12">
                            <label>DNI:</label>
                            <input asp-for="dni" type="text" class="form-control" />
                        </div>
                    </div>

                    <div class="row mt-2">
                        <div class="col-md-12">
                            <label>Nombres:</label>
                            <input asp-for="nombre" type="text" class="form-control" />
                        </div>
                    </div>

                    <div class="row mt-2">
                        <div class="col-md-12">
                            <label>Apellido:</label>
                            <input asp-for="apellido" type="text" class="form-control" />
                        </div>
                    </div>

                    <div class="row mt-2">
                        <div class="col-md-12">
                            <label>User:</label>
                            <input asp-for="usuario" type="text" class="form-control" />
                        </div>
                    </div>

                    <div class="row mt-2">
                        <div class="col-md-12">
                            <label>Password:</label>
                            <input asp-for="contrasena" type="password" class="form-control" />
                        </div>
                    </div>

                </div>
            </div>
        </div>

        <div class="col-md-6">

            <div class="row">
                <h5><i class="fa-solid fa-credit-card"></i> Información del pago</h5>
            </div>

            <div class="row mt-2">
                <div class="col-md-12">
                    <label>Tarjeta de Credito:</label>
                    <input asp-for="numerotarjeta" type="text" class="form-control" />
                </div>
            </div>

            <div class="row mt-2">
                <div class="col-md-8">
                    <label>Fecha expiración:</label>
                    <input asp-for="fechaexpiracion" type="text" class="form-control" placeholder="MM/YY" />
                </div>
                <div class="col-md-4">
                    <label>CVV:</label>
                    <input asp-for="cvv" type="text" class="form-control" />
                </div>
            </div>
            <div class="row mt-2">
                <div class="col-md-12">
                    <label>Correo:</label>
                    <input asp-for="correo" type="text" class="form-control" />
                </div>
            </div>
        </div>

    </div>

    <div class="row m-5">
        <div class="col-md-12">
            <center>

                <button type="submit" class="btn btn-success">Confirmar compra</button>

            </center>
        </div>
    </div>

</form>

avanceproyidk/Views/Carrito/DetalleProducto.cshtml
@model ProductosCatalogosModel
@{
    ViewData["Title"] = "DetalleProducto";
}

<h1>Detalle Producto</h1>

<section class="row mt-5">
    <input type="hidden" value="@Model.idproducto" id="hdnIdProducto" />

    <article class="col-md-4">
        <img class="card-img-top" src="@Model.imagen" alt="@Model.nombreproducto">
    </article>

    <article class="col-md-8">
        <section class="row">
            <article class="col-md-12">
                <h6 class="text-secondary">@Model.marca</h6>
            </article>
        </section>
        <section class="row">
            <article class="col-md-12">
                <h5>@Model.nombreproducto</h5>
            </article>
        </section>
        <section class="row">
            <article class="col-md-12">
                <p>
                    <i class="fa-solid fa-money-bill-1 text-success" style="font-size:50px;"></i>
                    <span class="text-secondary" style="font-size:40px; text-decoration: line-through;">@Model.precio</span>
                    <span class="text-success" style="font-size:60px;">@Model.preciofinal</span>
                    <span class="text-danger font-weight-bold">- @Model.descuento%</span>
                </p>

                <p>
                    <b>Descripción:</b> @Model.descripcion
                </p>

                <p>
                    <input class="form-control" id="txtCantidad" type="text" style="width:50px;" />
                </p>

                <button id="btnAnadir" class="btn btn-primary"><i class="fa-solid fa-cart-plus"></i> Añadir</button>

                <a asp-controller="Carrito" asp-action="ConfirmarCarrito" class="btn btn-danger"> Confirmar Compra</a>

                <a asp-controller="Carrito" asp-action="CatalogoProducto" class="btn btn-secondary"> Volver</a>
            </article>
        </section>
    </article>
</section>

@section Scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            $("#btnAnadir").click(() => { addTemporalProduct(); });
        });

        let addTemporalProduct = () => {
            let quantity = $("#txtCantidad").val();
            let productId = $("#hdnIdProducto").val();

            $.ajax({
                type: 'POST',
                url: '@Url.Action("AddProductoTemporal","Carrito")',
                data: {
                    "Id": productId,
                    "cantidad": quantity
                },
                success: () => {
                    alert("Se añadió el producto satisfactoriamente");
                    $("#txtCantidad").val("");
                },
                error: (ex, det) => {
                    console.log("ERROR =>", ex, det);
                }
            });
        }
    </script>
}

avanceproyidk/Views/Carrito/MsgOrdenExitosa.cshtml
@{
    ViewData["Title"] = "MsgOrdenExitosa";
}

<h1>Compra realizada con exito!!</h1>

<a asp-controller="Carrito" asp-action="CatalogoProducto" class="btn btn-secondary"> Volver</a>